#!/usr/bin/env php
<?php
/**
 * @author    Graphical House
 * @copyright Copyright (c) 2018 Graphical House
 * @link      https://www.graphicalhouse.co.uk//
 * @package   GraphicalHouse/craftyons
 * @since     1.0.0
 * @license   MIT
 */

use yii\helpers\Console;

use mikehaertl\shellcommand\Command as ShellCommand;

// const LoadingIndicator = ['braille-pattern-cli-loading-indicator')];

const INSTALL_PLUGINS = [
    'cp-field-inspect',
    'redactor',
    'typogrify',
];

const CRAFT_SCRIPTS_SETUP = [
    'srclink'      => 'vendor/nystudio107/craft-scripts/scripts',
    'destlink'     => 'scripts',
    'srcpath'      => 'scripts/craft3-example.env.sh',
    'destpath'     => '.env.sh',
    'replacements' => [
        'GLOBAL_DB_TABLE_PREFIX=""' => [
            'substr'  => '""',
            'env'     => 'DB_TABLE_PREFIX',
            'default' => '',
        ],
        'GLOBAL_DB_DRIVER="mysql"' => [
            'substr'  => '"mysql"',
            'env'     => 'DB_DRIVER',
            'default' => 'mysql',
        ],
        'LOCAL_ROOT_PATH="REPLACE_ME"' => [
            'substr'  => '"REPLACE_ME"',
            'env'     => '',
            'default' => '',
        ],
        'LOCAL_ASSETS_PATH=${LOCAL_ROOT_PATH}"REPLACE_ME"' => [
            'substr'  => '"REPLACE_ME"',
            'env'     => '',
            'default' => 'web/assets/',
        ],
        'LOCAL_DB_NAME="REPLACE_ME"' => [
            'substr'  => '"REPLACE_ME"',
            'env'     => 'DB_DATABASE',
            'default' => 'REPLACE_ME',
        ],
        'LOCAL_DB_PASSWORD="REPLACE_ME"' => [
            'substr'  => '"REPLACE_ME"',
            'env'     => 'DB_PASSWORD',
            'default' => 'REPLACE_ME',
        ],
        'LOCAL_DB_USER="REPLACE_ME"' => [
            'substr'  => '"REPLACE_ME"',
            'env'     => 'DB_USER',
            'default' => 'REPLACE_ME',
        ],
        'LOCAL_DB_HOST="localhost"' => [
            'substr'  => '"localhost"',
            'env'     => 'DB_SERVER',
            'default' => 'localhost',
        ],
        'LOCAL_DB_PORT="3306"' => [
            'substr'  => '"3306"',
            'env'     => 'DB_PORT',
            'default' => '3306',
        ],
        'LOCAL_DB_SCHEMA="public"' => [
            'substr'  => '"public"',
            'env'     => 'DB_SCHEMA',
            'default' => 'public',
        ],
    ],
];

// Set path constants
define('CRAFT_BASE_PATH', __DIR__);
define('CRAFT_VENDOR_PATH', CRAFT_BASE_PATH.'/vendor');

// Load Composer's autoloader
require_once CRAFT_VENDOR_PATH.'/autoload.php';

// Load the .env file Craft created
if (file_exists(CRAFT_BASE_PATH.'/.env')) {
    $dotEnv = new Dotenv\Dotenv(CRAFT_BASE_PATH);
    $dotEnv->load();
}

// By default, run the setup script
if (empty($argv[1])) {
    setupCraftyons();
} else {
    // See what command we were passed in
    switch ($argv[1]) {
        case 'welcome':
            // Display a welcome message
            welcomeCraftyons();
            break;

        case 'update':
            // Display a welcome message
            updateCraftyons();
            break;

        default:
            // Set up all the things!
            setupCraftyons();
            break;
    }
}

/**
 * Display a welcome message
 */
function welcomeCraftyons()
{
    outputString(PHP_EOL.'To set up your Craft install, from your project directory, run:', Console::FG_YELLOW);
    $script = './craft setup';
    outputString(PHP_EOL.'    '.$script, Console::FG_GREEN);
    outputString(PHP_EOL.'Then to set up Craftyons & nystudio107\'s Craft-Scripts, run:', Console::FG_YELLOW);
    $script = './craftyons-setup';
    outputString(PHP_EOL.'    '.$script, Console::FG_GREEN);
    outputString(PHP_EOL.'Your setup is not complete until you run these two commands.', Console::FG_YELLOW);
}

/**
 * Update our Craft-Scripts symlinks as needed!
 */
function updateCraftyons()
{
    // Say hello
    outputString(PHP_EOL.'Updating craftyons-setup', Console::FG_YELLOW);
    // Set up Craft-Scripts
    setupCraftScripts();
    // Say goodbye
    outputString(PHP_EOL.'Update complete. Have a nice day!', Console::FG_YELLOW);
}

/**
 * Set up all the things!
 */
function setupCraftyons()
{
    // Say hello
    outputString(PHP_EOL.'Welcome to the Craftyons setup', Console::FG_YELLOW);
    // Set up Craft-Scripts
    setupCraftScripts();
    // Setup Craft 3 Multi-Environment
    // setupCraftMultinstallNodePackagesiEnvironment();
    // Install the default plugins
    installPlugins();
    // Install the NodeJS packages
    installNodePackages();
    // Show installed NodeJS packages
    showNodePackages();
    // Set up Tachyons Generator and register new project with Valet
    setupTachyonsGeneratorandLaunch();
}

/**
 * Set up Craft-Scripts
 */
function setupCraftScripts()
{
    // Set up Craft-Scripts if the file scripts/.env.sh doesn't exist already
    outputString(PHP_EOL.'Setting up Craft-Scripts', Console::FG_YELLOW);
    if (!file_exists('scripts/.env.sh')) {
        $fileInfo = CRAFT_SCRIPTS_SETUP;
        // Create the scripts symlink
        createSymLink($fileInfo['srclink'], $fileInfo['destlink']);
        if (!file_exists('.env.sh')) {
            // Create the default .env.sh
            if (copyFile($fileInfo['srcpath'], $fileInfo['destpath'])) {
                $replacements = $fileInfo['replacements'];
                if (!empty($replacements)) {
                    // We need to swap in some dynamic variables for specific settings replacements
                    $replacements['LOCAL_ROOT_PATH="REPLACE_ME"']['default'] = CRAFT_BASE_PATH.DIRECTORY_SEPARATOR;
                    replaceInFile($fileInfo['destpath'], $replacements);
                }
            }
        }
        // Create the scripts/.env.sh symlink
        createSymLink(CRAFT_BASE_PATH.DIRECTORY_SEPARATOR.'.env.sh', 'scripts/.env.sh');
    } else {
        outputString('### scripts/.env.sh file already exists, exiting...', Console::FG_RED);
    }

}

/**
 * Install the default plugins
 */
function installPlugins()
{
    outputString(PHP_EOL.'Installing plugins', Console::FG_YELLOW);
    $installPluginCmd = './craft install/plugin ';
    foreach (INSTALL_PLUGINS as $pluginHandle) {
        outputString('- installing plugin '.$pluginHandle);
        executeShellCommand($installPluginCmd . $pluginHandle);
    }
}

function installNodePackages()
{
    $command = 'npm install';

    outputString(PHP_EOL.'Installing NodeJS packages via '.$command. ' (this may take quite some time...)', Console::FG_YELLOW);

    if (!empty($command)) {
        $result = executeShellCommand($command);
        outputString($result);
    } else {
        outputString('### unable to install NodeJS packages, npm not found', Console::FG_RED);
    }
}

function showNodePackages()
{
    $command = 'npm list -depth 0';

    outputString(PHP_EOL.'Showing installed NodeJS packages...', Console::FG_YELLOW);

    if (!empty($command)) {
        $result = executeShellCommand($command);
        outputString($result);
    } else {
        outputString('### unable to show NodeJS packages, npm not found', Console::FG_RED);
    }
}

function setupTachyonsGeneratorandLaunch()
{
    $command = 'cd node_modules/tachyons-custom && npm install && npm run build:css && cp css/tachyons.css ../../src/css && cd ../../ && ls && echo Tachyons moved to src folder, now launching website && valet link && valet secure && valet open';

    outputString(PHP_EOL.'Installing Tachyons Generator and setting up a local server using Laravel Valet, hold please...', Console::FG_YELLOW);

    if (!empty($command)) {
        $result = executeShellCommand($command);
        outputString($result);
    } else {
        outputString('### unable to show NodeJS packages, npm not found', Console::FG_RED);
    }
}


/**
 * Output a string to the console, using optional $args to color it, if supported
 *
 * @param string $string
 *
 * @return mixed
 */
function outputString($string)
{
    $stream = \STDOUT;
    if (Console::streamSupportsAnsiColors($stream)) {
        $args = func_get_args();
        array_shift($args);
        $string = Console::ansiFormat($string, $args);
    }

    return Console::stdout($string.PHP_EOL);
}

/**
 * Create a symlink from $srcPath to $destPath
 *
 * @param string $srcPath
 * @param string $destPath
 *
 * @return bool
 */
function createSymLink(string $srcPath, string $destPath)
{
    $result = @symlink($srcPath, $destPath);
    if ($result) {
        outputString('- created symlink from '.$srcPath.' to '.$destPath);
    } else {
        outputString('### error creating symlink from '.$srcPath.' to '.$destPath, Console::FG_RED);
    }

    return $result;
}

/**
 * Copy the $srcPath file to $destPath
 *
 * @param string $srcPath
 * @param string $destPath
 *
 * @return bool
 */
function copyFile(string $srcPath, string $destPath)
{
    $result = @copy($srcPath, $destPath);
    if ($result) {
        outputString('- copied '.$srcPath.' to '.$destPath);
    } else {
        outputString('### error copying '.$srcPath.' to '.$destPath, Console::FG_RED);
    }

    return $result;
}

/**
 * Replace strings in $filePath and write out the modified file
 *
 * @param string $filePath
 * @param array  $replacements
 */
function replaceInFile(string $filePath, array $replacements)
{
    if (!empty($replacements)) {
        outputString('- setting up '.$filePath);
        $fileContents = file_get_contents($filePath);
        foreach ($replacements as $findValue => $params) {
            $replaceValue = empty($params['env']) ? $params['default'] : getenv($params['env']) ?? $params['default'];
            if (!empty($params['substr'])) {
                $subStr = $params['substr'];
                $wrapChar = '';
                // If the $subStr is quoted, quote the $replaceValue, too
                if ($subStr[0] == "'" || $subStr[0] == '"') {
                    $wrapChar = $subStr[0];
                }
                $replaceValue = str_replace($subStr, $wrapChar.$replaceValue.$wrapChar, $findValue);
            }
            $fileContents = str_replace($findValue, $replaceValue, $fileContents);
        }
        // Write the file out
        file_put_contents($filePath, $fileContents);
    }
}

/**
 * Execute a shell command
 *
 * @param string $command
 *
 * @return string
 */
function executeShellCommand(string $command): string
{
    // Create the shell command
    $shellCommand = new ShellCommand();
    $shellCommand->setCommand($command);

    // If we don't have proc_open, maybe we've got exec
    if (!function_exists('proc_open') && function_exists('exec')) {
        $shellCommand->useExec = true;
    }

    // Return the result of the command's output or error
    if ($shellCommand->execute()) {
        $result = $shellCommand->getOutput();
    } else {
        $result = $shellCommand->getError();
    }

    return $result;
}

/**
 * Return whether a shell command exists ir not
 *
 * @param string $command
 *
 * @return bool
 */
function shellCommandExists(string $command): bool
{
    $result = executeShellCommand('which '.$command);

    return !empty($result);
}
